### ISSUE TITLE
clearinghouse error

### ISSUE THREAD

**Issue by raymondfx** [synechron-finlabs/Three-parties-DvP-Atomic-TX-CorDapp#2]
I am getting this error 
 `flow start com.synechron.cordapp.clearinghouse.flows.AssetSettlementInitiatorFlow linearId: "<Replace with AssetTransfer.linearId.id>"`
```
No matching constructor found:
- [UniqueIdentifier]: Could not parse as a command: Invalid UUID string: <Replace with AssetTransfer.linearId.id>
```

**Comment by balajimore** [comment]
You have to replace string `<Replace with AssetTransfer.linearId.id>` with valid value of `AssetTransfer.linearId.id` field.  
You can get available `AssetTransfer` states by running below commands on the shell of `ClearningHouse`:
`run vaultQuery contractStateType: com.synechron.cordapp.state.AssetTransfer`
